package net.adriantodt.winged

import net.adriantodt.winged.data.Wing
import net.adriantodt.winged.item.WingItem
import net.minecraft.util.Identifier

val ELYTRA_WING = Wing(mcIdentifier("textures/entity/elytra.png"), "Mojang")
val MOJANG_CAPE_WING = Wing(identifier("textures/entity/mojang_cape_wing.png"), "Mojang")
val MOJANG_CAPE_WING_ALT = Wing(identifier("textures/entity/mojang_cape_wing_alt.png"), "Mojang")
val MINECON_2011_CAPE_WING = Wing(identifier("textures/entity/minecon_2011_cape_wing.png"), "Mojang")
val MINECON_2012_CAPE_WING = Wing(identifier("textures/entity/minecon_2012_cape_wing.png"), "Mojang")
val MINECON_2013_CAPE_WING = Wing(identifier("textures/entity/minecon_2013_cape_wing.png"), "Mojang")
val MINECON_2015_CAPE_WING = Wing(identifier("textures/entity/minecon_2015_cape_wing.png"), "Mojang")
val MINECON_2016_CAPE_WING = Wing(identifier("textures/entity/minecon_2016_cape_wing.png"), "Mojang")
val MINECON_2019_CAPE_WING = Wing(identifier("textures/entity/minecon_2019_cape_wing.png"), "Mojang")
val COBALT_CAPE_WING = Wing(identifier("textures/entity/cobalt_cape_wing.png"), "Mojang")
val CROWDIN_CAPE_WING = Wing(identifier("textures/entity/crowdin_cape_wing.png"), "Mojang")
val MAPMAKER_CAPE_WING = Wing(identifier("textures/entity/mapmaker_cape_wing.png"), "Mojang")
val MILLIONTH_CAPE_WING = Wing(identifier("textures/entity/millionth_cape_wing.png"), "Mojang")
val MOJIRA_MOD_CAPE_WING = Wing(identifier("textures/entity/mojira_mod_cape_wing.png"), "Mojang")
val DANNYBSTYLE_CAPE_WING = Wing(identifier("textures/entity/dannybstyle_cape_wing.png"), "Mojang")
val JULIANCLARK_CAPE_WING = Wing(identifier("textures/entity/julianclark_cape_wing.png"), "Mojang")
val JULIANCLARK_CAPE_WING_ALT = Wing(identifier("textures/entity/julianclark_cape_wing_alt.png"), "Mojang")
val MRMESSIAH_CAPE_WING = Wing(identifier("textures/entity/mrmessiah_cape_wing.png"), "Mojang")
val PRISMARINE_CAPE_WING = Wing(identifier("textures/entity/prismarine_cape_wing.png"), "Mojang")
val TURTLE_CAPE_WING = Wing(identifier("textures/entity/turtle_cape_wing.png"), "Mojang")
val EAGLE_WING = Wing(identifier("textures/entity/eagle_wing.png"), "Lemoncake")
val GREENWING_MACAW_WING = Wing(identifier("textures/entity/greenwing_macaw_wing.png"), "Lemoncake")
val FAIRYONLINE_WING = Wing(identifier("textures/entity/fairyonline_wing.png"), "Lemoncake")
val FRIED_CHICKEN_WING = Wing(identifier("textures/entity/fried_chicken_wing.png"), "Lemoncake")
val FIRE_DRAGON_WING = Wing(identifier("textures/entity/fire_dragon_wing.png"), "Lemoncake, AdrianTodt")
val PHANTOM_WING = Wing(identifier("textures/entity/phantom_wing.png"), "Noatry")
val PHANTOM_WING_ALT = Wing(identifier("textures/entity/phantom_wing_alt.png"), "Shosh99")
val PHANTOM_MEMBRANE_WING = Wing(identifier("textures/entity/phantom_membrane_wing.png"), "Trailblazer101")
val BAT_WING = Wing(identifier("textures/entity/bat_wing.png"), "Lemoncake")
val BAT_WING_ALT = Wing(identifier("textures/entity/bat_wing_alt.png"), "Doctor_CZ")
val VEX_WING = Wing(identifier("textures/entity/vex_wing.png"), "The_Khuzdul1")
val CREAMY_WHITE_WING = Wing(identifier("textures/entity/creamy_white_wing.png"), "nightb0x")
val MECH_DRAGON_WING = Wing(identifier("textures/entity/mech_dragon_wing.png"), "Ontvlambaar")
val REDSTONE_WING = Wing(identifier("textures/entity/redstone_wing.png"), "dbrighthd")
val SHULKER_WING = Wing(identifier("textures/entity/shulker_wing.png"), "dbrighthd")
val TNT_WING = Wing(identifier("textures/entity/tnt_wing.png"), "dbrighthd")
val TINY_BIRD_WING = Wing(identifier("textures/entity/tiny_bird_wing.png"), "dbrighthd")
val BRAZIL_WING = Wing(identifier("textures/entity/brazil_wing.png"), "dbrighthd")
val USA_WING = Wing(identifier("textures/entity/usa_wing.png"), "dbrighthd")
val EARTH_WING = Wing(identifier("textures/entity/earth_wing.png"), "Ontvlambaar")
val RAINBOW_WING = Wing(identifier("textures/entity/rainbow_wing.png"), "dbrighthd")
val BLACK_ELYTRA_WING = Wing(identifier("textures/entity/black_elytra_wing.png"), "dbrighthd")
val BLUE_ELYTRA_WING = Wing(identifier("textures/entity/blue_elytra_wing.png"), "dbrighthd")
val BROWN_ELYTRA_WING = Wing(identifier("textures/entity/brown_elytra_wing.png"), "dbrighthd")
val CYAN_ELYTRA_WING = Wing(identifier("textures/entity/cyan_elytra_wing.png"), "dbrighthd")
val GRAY_ELYTRA_WING = Wing(identifier("textures/entity/gray_elytra_wing.png"), "dbrighthd")
val GREEN_ELYTRA_WING = Wing(identifier("textures/entity/green_elytra_wing.png"), "dbrighthd")
val LIGHT_BLUE_ELYTRA_WING = Wing(identifier("textures/entity/light_blue_elytra_wing.png"), "dbrighthd")
val LIGHT_GRAY_ELYTRA_WING = Wing(identifier("textures/entity/light_gray_elytra_wing.png"), "dbrighthd")
val LIME_ELYTRA_WING = Wing(identifier("textures/entity/lime_elytra_wing.png"), "dbrighthd")
val MAGENTA_ELYTRA_WING = Wing(identifier("textures/entity/magenta_elytra_wing.png"), "dbrighthd")
val ORANGE_ELYTRA_WING = Wing(identifier("textures/entity/orange_elytra_wing.png"), "dbrighthd")
val PINK_ELYTRA_WING = Wing(identifier("textures/entity/pink_elytra_wing.png"), "dbrighthd")
val PURPLE_ELYTRA_WING = Wing(identifier("textures/entity/purple_elytra_wing.png"), "dbrighthd")
val RED_ELYTRA_WING = Wing(identifier("textures/entity/red_elytra_wing.png"), "dbrighthd")
val WHITE_ELYTRA_WING = Wing(identifier("textures/entity/white_elytra_wing.png"), "dbrighthd")
val YELLOW_ELYTRA_WING = Wing(identifier("textures/entity/yellow_elytra_wing.png"), "dbrighthd")

val ITEM_WING_ELYTRA = makeWingItem(mcIdentifier("elytra").wing(ELYTRA_WING))
val ITEM_WING_MOJANG_CAPE = makeWingItem(identifier("mojang_cape_wing").wing(MOJANG_CAPE_WING))
val ITEM_WING_MOJANG_CAPE_ALT = makeWingItem(identifier("mojang_cape_wing_alt").wing(MOJANG_CAPE_WING_ALT))
val ITEM_WING_MINECON_2011_CAPE = makeWingItem(identifier("minecon_2011_cape_wing").wing(MINECON_2011_CAPE_WING))
val ITEM_WING_MINECON_2012_CAPE = makeWingItem(identifier("minecon_2012_cape_wing").wing(MINECON_2012_CAPE_WING))
val ITEM_WING_MINECON_2013_CAPE = makeWingItem(identifier("minecon_2013_cape_wing").wing(MINECON_2013_CAPE_WING))
val ITEM_WING_MINECON_2015_CAPE = makeWingItem(identifier("minecon_2015_cape_wing").wing(MINECON_2015_CAPE_WING))
val ITEM_WING_MINECON_2016_CAPE = makeWingItem(identifier("minecon_2016_cape_wing").wing(MINECON_2016_CAPE_WING))
val ITEM_WING_MINECON_2019_CAPE = makeWingItem(identifier("minecon_2019_cape_wing").wing(MINECON_2019_CAPE_WING))
val ITEM_WING_COBALT_CAPE = makeWingItem(identifier("cobalt_cape_wing").wing(COBALT_CAPE_WING))
val ITEM_WING_CROWDIN_CAPE = makeWingItem(identifier("crowdin_cape_wing").wing(CROWDIN_CAPE_WING))
val ITEM_WING_MAPMAKER_CAPE = makeWingItem(identifier("mapmaker_cape_wing").wing(MAPMAKER_CAPE_WING))
val ITEM_WING_MILLIONTH_CAPE = makeWingItem(identifier("millionth_cape_wing").wing(MILLIONTH_CAPE_WING))
val ITEM_WING_MOJIRA_MOD_CAPE = makeWingItem(identifier("mojira_mod_cape_wing").wing(MOJIRA_MOD_CAPE_WING))
val ITEM_WING_DANNYBSTYLE_CAPE = makeWingItem(identifier("dannybstyle_cape_wing").wing(DANNYBSTYLE_CAPE_WING))
val ITEM_WING_JULIANCLARK_CAPE = makeWingItem(identifier("julianclark_cape_wing").wing(JULIANCLARK_CAPE_WING))
val ITEM_WING_JULIANCLARK_CAPE_ALT =
    makeWingItem(identifier("julianclark_cape_wing_alt").wing(JULIANCLARK_CAPE_WING_ALT))
val ITEM_WING_MRMESSIAH_CAPE = makeWingItem(identifier("mrmessiah_cape_wing").wing(MRMESSIAH_CAPE_WING))
val ITEM_WING_PRISMARINE_CAPE = makeWingItem(identifier("prismarine_cape_wing").wing(PRISMARINE_CAPE_WING))
val ITEM_WING_TURTLE_CAPE = makeWingItem(identifier("turtle_cape_wing").wing(TURTLE_CAPE_WING))
val ITEM_WING_EAGLE = makeWingItem(identifier("eagle_wing").wing(EAGLE_WING))
val ITEM_WING_GREENWING_MACAW = makeWingItem(identifier("greenwing_macaw_wing").wing(GREENWING_MACAW_WING))
val ITEM_WING_FAIRYONLINE = makeWingItem(identifier("fairyonline_wing").wing(FAIRYONLINE_WING))
val ITEM_WING_FRIED_CHICKEN = makeWingItem(identifier("fried_chicken_wing").wing(FRIED_CHICKEN_WING))
val ITEM_WING_FIRE_DRAGON = makeWingItem(identifier("fire_dragon_wing").wing(FIRE_DRAGON_WING))
val ITEM_WING_PHANTOM = makeWingItem(identifier("phantom_wing").wing(PHANTOM_WING))
val ITEM_WING_PHANTOM_MEMBRANE = makeWingItem(identifier("phantom_membrane_wing").wing(PHANTOM_MEMBRANE_WING))
val ITEM_WING_PHANTOM_ALT = makeWingItem(identifier("phantom_wing_alt").wing(PHANTOM_WING_ALT))
val ITEM_WING_BAT = makeWingItem(identifier("bat_wing").wing(BAT_WING))
val ITEM_WING_BAT_ALT = makeWingItem(identifier("bat_wing_alt").wing(BAT_WING_ALT))
val ITEM_WING_MECH_DRAGON = makeWingItem(identifier("mech_dragon_wing").wing(MECH_DRAGON_WING))
val ITEM_WING_REDSTONE = makeWingItem(identifier("redstone_wing").wing(REDSTONE_WING))
val ITEM_WING_SHULKER = makeWingItem(identifier("shulker_wing").wing(SHULKER_WING))
val ITEM_WING_TNT = makeWingItem(identifier("tnt_wing").wing(TNT_WING))
val ITEM_WING_TINY_BIRD = makeWingItem(identifier("tiny_bird_wing").wing(TINY_BIRD_WING))
val ITEM_WING_VEX = makeWingItem(identifier("vex_wing").wing(VEX_WING))
val ITEM_WING_CREAMY_WHITE = makeWingItem(identifier("creamy_white_wing").wing(CREAMY_WHITE_WING))
val ITEM_WING_BRAZIL = makeWingItem(identifier("brazil_wing").wing(BRAZIL_WING))
val ITEM_WING_USA = makeWingItem(identifier("usa_wing").wing(USA_WING))
val ITEM_WING_EARTH = makeWingItem(identifier("earth_wing").wing(EARTH_WING))
val ITEM_WING_RAINBOW = makeWingItem(identifier("rainbow_wing").wing(RAINBOW_WING))
val ITEM_WING_ELYTRA_WHITE = makeWingItem(identifier("white_elytra_wing").wing(WHITE_ELYTRA_WING))
val ITEM_WING_ELYTRA_ORANGE = makeWingItem(identifier("orange_elytra_wing").wing(ORANGE_ELYTRA_WING))
val ITEM_WING_ELYTRA_MAGENTA = makeWingItem(identifier("magenta_elytra_wing").wing(MAGENTA_ELYTRA_WING))
val ITEM_WING_ELYTRA_LIGHT_BLUE = makeWingItem(identifier("light_blue_elytra_wing").wing(LIGHT_BLUE_ELYTRA_WING))
val ITEM_WING_ELYTRA_YELLOW = makeWingItem(identifier("yellow_elytra_wing").wing(YELLOW_ELYTRA_WING))
val ITEM_WING_ELYTRA_LIME = makeWingItem(identifier("lime_elytra_wing").wing(LIME_ELYTRA_WING))
val ITEM_WING_ELYTRA_PINK = makeWingItem(identifier("pink_elytra_wing").wing(PINK_ELYTRA_WING))
val ITEM_WING_ELYTRA_GRAY = makeWingItem(identifier("gray_elytra_wing").wing(GRAY_ELYTRA_WING))
val ITEM_WING_ELYTRA_LIGHT_GRAY = makeWingItem(identifier("light_gray_elytra_wing").wing(LIGHT_GRAY_ELYTRA_WING))
val ITEM_WING_ELYTRA_CYAN = makeWingItem(identifier("cyan_elytra_wing").wing(CYAN_ELYTRA_WING))
val ITEM_WING_ELYTRA_PURPLE = makeWingItem(identifier("purple_elytra_wing").wing(PURPLE_ELYTRA_WING))
val ITEM_WING_ELYTRA_BLUE = makeWingItem(identifier("blue_elytra_wing").wing(BLUE_ELYTRA_WING))
val ITEM_WING_ELYTRA_BROWN = makeWingItem(identifier("brown_elytra_wing").wing(BROWN_ELYTRA_WING))
val ITEM_WING_ELYTRA_GREEN = makeWingItem(identifier("green_elytra_wing").wing(GREEN_ELYTRA_WING))
val ITEM_WING_ELYTRA_RED = makeWingItem(identifier("red_elytra_wing").wing(RED_ELYTRA_WING))
val ITEM_WING_ELYTRA_BLACK = makeWingItem(identifier("black_elytra_wing").wing(BLACK_ELYTRA_WING))

fun makeWingItem(identifier: Identifier) = WingItem(wingItemSettings(), identifier)

fun initWings() {
    identifier("wing_elytra").item(ITEM_WING_ELYTRA)
    identifier("wing_mojang_cape").item(ITEM_WING_MOJANG_CAPE)
    identifier("wing_mojang_cape_alt").item(ITEM_WING_MOJANG_CAPE_ALT)
    identifier("wing_minecon_2011_cape").item(ITEM_WING_MINECON_2011_CAPE)
    identifier("wing_minecon_2012_cape").item(ITEM_WING_MINECON_2012_CAPE)
    identifier("wing_minecon_2013_cape").item(ITEM_WING_MINECON_2013_CAPE)
    identifier("wing_minecon_2015_cape").item(ITEM_WING_MINECON_2015_CAPE)
    identifier("wing_minecon_2016_cape").item(ITEM_WING_MINECON_2016_CAPE)
    identifier("wing_minecon_2019_cape").item(ITEM_WING_MINECON_2019_CAPE)
    identifier("wing_cobalt_cape").item(ITEM_WING_COBALT_CAPE)
    identifier("wing_crowdin_cape").item(ITEM_WING_CROWDIN_CAPE)
    identifier("wing_mapmaker_cape").item(ITEM_WING_MAPMAKER_CAPE)
    identifier("wing_millionth_cape").item(ITEM_WING_MILLIONTH_CAPE)
    identifier("wing_mojira_mod_cape").item(ITEM_WING_MOJIRA_MOD_CAPE)
    identifier("wing_dannybstyle_cape").item(ITEM_WING_DANNYBSTYLE_CAPE)
    identifier("wing_julianclark_cape").item(ITEM_WING_JULIANCLARK_CAPE)
    identifier("wing_julianclark_cape_alt").item(ITEM_WING_JULIANCLARK_CAPE_ALT)
    identifier("wing_mrmessiah_cape").item(ITEM_WING_MRMESSIAH_CAPE)
    identifier("wing_prismarine_cape").item(ITEM_WING_PRISMARINE_CAPE)
    identifier("wing_turtle_cape").item(ITEM_WING_TURTLE_CAPE)
    identifier("wing_eagle").item(ITEM_WING_EAGLE)
    identifier("wing_greenwing_macaw").item(ITEM_WING_GREENWING_MACAW)
    identifier("wing_fried_chicken").item(ITEM_WING_FRIED_CHICKEN)
    identifier("wing_fairyonline").item(ITEM_WING_FAIRYONLINE)
    identifier("wing_fire_dragon").item(ITEM_WING_FIRE_DRAGON)
    identifier("wing_phantom").item(ITEM_WING_PHANTOM)
    identifier("wing_phantom_alt").item(ITEM_WING_PHANTOM_ALT)
    identifier("wing_phantom_membrane").item(ITEM_WING_PHANTOM_MEMBRANE)
    identifier("wing_bat").item(ITEM_WING_BAT)
    identifier("wing_bat_alt").item(ITEM_WING_BAT_ALT)
    identifier("wing_mech_dragon").item(ITEM_WING_MECH_DRAGON)
    identifier("wing_redstone").item(ITEM_WING_REDSTONE)
    identifier("wing_shulker").item(ITEM_WING_SHULKER)
    identifier("wing_tnt").item(ITEM_WING_TNT)
    identifier("wing_tiny_bird").item(ITEM_WING_TINY_BIRD)
    identifier("wing_vex").item(ITEM_WING_VEX)
    identifier("wing_creamy_white").item(ITEM_WING_CREAMY_WHITE)
    identifier("wing_brazil").item(ITEM_WING_BRAZIL)
    identifier("wing_usa").item(ITEM_WING_USA)
    identifier("wing_earth").item(ITEM_WING_EARTH)
    identifier("wing_rainbow").item(ITEM_WING_RAINBOW)
    identifier("wing_elytra_white").item(ITEM_WING_ELYTRA_WHITE)
    identifier("wing_elytra_orange").item(ITEM_WING_ELYTRA_ORANGE)
    identifier("wing_elytra_magenta").item(ITEM_WING_ELYTRA_MAGENTA)
    identifier("wing_elytra_light_blue").item(ITEM_WING_ELYTRA_LIGHT_BLUE)
    identifier("wing_elytra_yellow").item(ITEM_WING_ELYTRA_YELLOW)
    identifier("wing_elytra_lime").item(ITEM_WING_ELYTRA_LIME)
    identifier("wing_elytra_pink").item(ITEM_WING_ELYTRA_PINK)
    identifier("wing_elytra_gray").item(ITEM_WING_ELYTRA_GRAY)
    identifier("wing_elytra_light_gray").item(ITEM_WING_ELYTRA_LIGHT_GRAY)
    identifier("wing_elytra_cyan").item(ITEM_WING_ELYTRA_CYAN)
    identifier("wing_elytra_purple").item(ITEM_WING_ELYTRA_PURPLE)
    identifier("wing_elytra_blue").item(ITEM_WING_ELYTRA_BLUE)
    identifier("wing_elytra_brown").item(ITEM_WING_ELYTRA_BROWN)
    identifier("wing_elytra_green").item(ITEM_WING_ELYTRA_GREEN)
    identifier("wing_elytra_red").item(ITEM_WING_ELYTRA_RED)
    identifier("wing_elytra_black").item(ITEM_WING_ELYTRA_BLACK)
}