package net.adriantodt.winged

import net.adriantodt.winged.data.Wing
import net.adriantodt.winged.item.WingItem

val ELYTRA_WING = Wing(mcIdentifier("textures/entity/elytra.png"), "Mojang")
val FIRE_DRAGON_WING = Wing(identifier("textures/entity/fire_dragon_wing.png"), "Lemoncake, AdrianTodt")
val PHANTOM_WING = Wing(identifier("textures/entity/phantom_wing.png"), "Noatry")
val PHANTOM_WING_ALT = Wing(identifier("textures/entity/phantom_wing_alt.png"), "Shosh99")
val BAT_WING = Wing(identifier("textures/entity/bat_wing.png"), "Lemoncake")
val BAT_WING_ALT = Wing(identifier("textures/entity/bat_wing_alt.png"), "Doctor_CZ")
val VEX_WING = Wing(identifier("textures/entity/vex_wing.png"), "The_Khuzdul1")
val CREAMY_WHITE_WING = Wing(identifier("textures/entity/creamy_white_wing.png"), "nightb0x")
val REDSTONE_WING = Wing(identifier("textures/entity/redstone_wing.png"), "dbrighthd")
val SHULKER_WING = Wing(identifier("textures/entity/shulker_wing.png"), "dbrighthd")
val TNT_WING = Wing(identifier("textures/entity/tnt_wing.png"), "dbrighthd")
val TINY_BIRD_WING = Wing(identifier("textures/entity/tiny_bird_wing.png"), "dbrighthd")
val BRAZIL_WING = Wing(identifier("textures/entity/brazil_wing.png"), "dbrighthd")
val USA_WING = Wing(identifier("textures/entity/usa_wing.png"), "dbrighthd")
val RAINBOW_WING = Wing(identifier("textures/entity/rainbow_wing.png"), "dbrighthd")
val BLACK_ELYTRA_WING = Wing(identifier("textures/entity/black_elytra_wing.png"), "dbrighthd")
val BLUE_ELYTRA_WING = Wing(identifier("textures/entity/blue_elytra_wing.png"), "dbrighthd")
val BROWN_ELYTRA_WING = Wing(identifier("textures/entity/brown_elytra_wing.png"), "dbrighthd")
val CYAN_ELYTRA_WING = Wing(identifier("textures/entity/cyan_elytra_wing.png"), "dbrighthd")
val GRAY_ELYTRA_WING = Wing(identifier("textures/entity/gray_elytra_wing.png"), "dbrighthd")
val GREEN_ELYTRA_WING = Wing(identifier("textures/entity/green_elytra_wing.png"), "dbrighthd")
val LIGHT_BLUE_ELYTRA_WING = Wing(identifier("textures/entity/light_blue_elytra_wing.png"), "dbrighthd")
val LIGHT_GRAY_ELYTRA_WING = Wing(identifier("textures/entity/light_gray_elytra_wing.png"), "dbrighthd")
val LIME_ELYTRA_WING = Wing(identifier("textures/entity/lime_elytra_wing.png"), "dbrighthd")
val MAGENTA_ELYTRA_WING = Wing(identifier("textures/entity/magenta_elytra_wing.png"), "dbrighthd")
val ORANGE_ELYTRA_WING = Wing(identifier("textures/entity/orange_elytra_wing.png"), "dbrighthd")
val PINK_ELYTRA_WING = Wing(identifier("textures/entity/pink_elytra_wing.png"), "dbrighthd")
val PURPLE_ELYTRA_WING = Wing(identifier("textures/entity/purple_elytra_wing.png"), "dbrighthd")
val RED_ELYTRA_WING = Wing(identifier("textures/entity/red_elytra_wing.png"), "dbrighthd")
val WHITE_ELYTRA_WING = Wing(identifier("textures/entity/white_elytra_wing.png"), "dbrighthd")
val YELLOW_ELYTRA_WING = Wing(identifier("textures/entity/yellow_elytra_wing.png"), "dbrighthd")

val ITEM_WING_ELYTRA = WingItem(wingItemSettings(), mcIdentifier("elytra").wing(ELYTRA_WING))
val ITEM_WING_FIRE_DRAGON = WingItem(wingItemSettings(), identifier("fire_dragon_wing").wing(FIRE_DRAGON_WING))
val ITEM_WING_PHANTOM = WingItem(wingItemSettings(), identifier("phantom_wing").wing(PHANTOM_WING))
val ITEM_WING_PHANTOM_ALT = WingItem(wingItemSettings(), identifier("phantom_wing_alt").wing(PHANTOM_WING_ALT))
val ITEM_WING_BAT = WingItem(wingItemSettings(), identifier("bat_wing").wing(BAT_WING))
val ITEM_WING_BAT_ALT = WingItem(wingItemSettings(), identifier("bat_wing_alt").wing(BAT_WING_ALT))
val ITEM_WING_REDSTONE = WingItem(wingItemSettings(), identifier("redstone_wing").wing(REDSTONE_WING))
val ITEM_WING_SHULKER = WingItem(wingItemSettings(), identifier("shulker_wing").wing(SHULKER_WING))
val ITEM_WING_TNT = WingItem(wingItemSettings(), identifier("tnt_wing").wing(TNT_WING))
val ITEM_WING_TINY_BIRD = WingItem(wingItemSettings(), identifier("tiny_bird_wing").wing(TINY_BIRD_WING))
val ITEM_WING_VEX = WingItem(wingItemSettings(), identifier("vex_wing").wing(VEX_WING))
val ITEM_WING_CREAMY_WHITE = WingItem(wingItemSettings(), identifier("creamy_white_wing").wing(CREAMY_WHITE_WING))
val ITEM_WING_BRAZIL = WingItem(wingItemSettings(), identifier("brazil_wing").wing(BRAZIL_WING))
val ITEM_WING_USA = WingItem(wingItemSettings(), identifier("usa_wing").wing(USA_WING))
val ITEM_WING_RAINBOW = WingItem(wingItemSettings(), identifier("rainbow_wing").wing(RAINBOW_WING))
val ITEM_WING_ELYTRA_WHITE = WingItem(wingItemSettings(), identifier("white_elytra_wing").wing(WHITE_ELYTRA_WING))
val ITEM_WING_ELYTRA_ORANGE = WingItem(wingItemSettings(), identifier("orange_elytra_wing").wing(ORANGE_ELYTRA_WING))
val ITEM_WING_ELYTRA_MAGENTA = WingItem(wingItemSettings(), identifier("magenta_elytra_wing").wing(MAGENTA_ELYTRA_WING))
val ITEM_WING_ELYTRA_LIGHT_BLUE =
    WingItem(wingItemSettings(), identifier("light_blue_elytra_wing").wing(LIGHT_BLUE_ELYTRA_WING))
val ITEM_WING_ELYTRA_YELLOW = WingItem(wingItemSettings(), identifier("yellow_elytra_wing").wing(YELLOW_ELYTRA_WING))
val ITEM_WING_ELYTRA_LIME = WingItem(wingItemSettings(), identifier("lime_elytra_wing").wing(LIME_ELYTRA_WING))
val ITEM_WING_ELYTRA_PINK = WingItem(wingItemSettings(), identifier("pink_elytra_wing").wing(PINK_ELYTRA_WING))
val ITEM_WING_ELYTRA_GRAY = WingItem(wingItemSettings(), identifier("gray_elytra_wing").wing(GRAY_ELYTRA_WING))
val ITEM_WING_ELYTRA_LIGHT_GRAY =
    WingItem(wingItemSettings(), identifier("light_gray_elytra_wing").wing(LIGHT_GRAY_ELYTRA_WING))
val ITEM_WING_ELYTRA_CYAN = WingItem(wingItemSettings(), identifier("cyan_elytra_wing").wing(CYAN_ELYTRA_WING))
val ITEM_WING_ELYTRA_PURPLE = WingItem(wingItemSettings(), identifier("purple_elytra_wing").wing(PURPLE_ELYTRA_WING))
val ITEM_WING_ELYTRA_BLUE = WingItem(wingItemSettings(), identifier("blue_elytra_wing").wing(BLUE_ELYTRA_WING))
val ITEM_WING_ELYTRA_BROWN = WingItem(wingItemSettings(), identifier("brown_elytra_wing").wing(BROWN_ELYTRA_WING))
val ITEM_WING_ELYTRA_GREEN = WingItem(wingItemSettings(), identifier("green_elytra_wing").wing(GREEN_ELYTRA_WING))
val ITEM_WING_ELYTRA_RED = WingItem(wingItemSettings(), identifier("red_elytra_wing").wing(RED_ELYTRA_WING))
val ITEM_WING_ELYTRA_BLACK = WingItem(wingItemSettings(), identifier("black_elytra_wing").wing(BLACK_ELYTRA_WING))

fun initWings() {
    identifier("wing_elytra").item(ITEM_WING_ELYTRA)
    identifier("wing_fire_dragon").item(ITEM_WING_FIRE_DRAGON)
    identifier("wing_phantom").item(ITEM_WING_PHANTOM)
    identifier("wing_phantom_alt").item(ITEM_WING_PHANTOM_ALT)
    identifier("wing_bat").item(ITEM_WING_BAT)
    identifier("wing_bat_alt").item(ITEM_WING_BAT_ALT)
    identifier("wing_redstone").item(ITEM_WING_REDSTONE)
    identifier("wing_shulker").item(ITEM_WING_SHULKER)
    identifier("wing_tnt").item(ITEM_WING_TNT)
    identifier("wing_tiny_bird").item(ITEM_WING_TINY_BIRD)
    identifier("wing_vex").item(ITEM_WING_VEX)
    identifier("wing_creamy_white").item(ITEM_WING_CREAMY_WHITE)
    identifier("wing_brazil").item(ITEM_WING_BRAZIL)
    identifier("wing_usa").item(ITEM_WING_USA)
    identifier("wing_rainbow").item(ITEM_WING_RAINBOW)
    identifier("wing_elytra_white").item(ITEM_WING_ELYTRA_WHITE)
    identifier("wing_elytra_orange").item(ITEM_WING_ELYTRA_ORANGE)
    identifier("wing_elytra_magenta").item(ITEM_WING_ELYTRA_MAGENTA)
    identifier("wing_elytra_light_blue").item(ITEM_WING_ELYTRA_LIGHT_BLUE)
    identifier("wing_elytra_yellow").item(ITEM_WING_ELYTRA_YELLOW)
    identifier("wing_elytra_lime").item(ITEM_WING_ELYTRA_LIME)
    identifier("wing_elytra_pink").item(ITEM_WING_ELYTRA_PINK)
    identifier("wing_elytra_gray").item(ITEM_WING_ELYTRA_GRAY)
    identifier("wing_elytra_light_gray").item(ITEM_WING_ELYTRA_LIGHT_GRAY)
    identifier("wing_elytra_cyan").item(ITEM_WING_ELYTRA_CYAN)
    identifier("wing_elytra_purple").item(ITEM_WING_ELYTRA_PURPLE)
    identifier("wing_elytra_blue").item(ITEM_WING_ELYTRA_BLUE)
    identifier("wing_elytra_brown").item(ITEM_WING_ELYTRA_BROWN)
    identifier("wing_elytra_green").item(ITEM_WING_ELYTRA_GREEN)
    identifier("wing_elytra_red").item(ITEM_WING_ELYTRA_RED)
    identifier("wing_elytra_black").item(ITEM_WING_ELYTRA_BLACK)
}