package net.adriantodt.winged

import net.adriantodt.winged.data.Wing

@Suppress("MemberVisibilityCanBePrivate")
object Wings {
    val elytra = Wing(mcIdentifier("textures/entity/elytra.png"), "Mojang")
    val mojangCape = Wing(wingTexture("mojang_cape_wing"), "Mojang")
    val mojangCapeAlt = Wing(wingTexture("mojang_cape_wing_alt"), "Mojang")
    val minecon2011Cape = Wing(wingTexture("minecon_2011_cape_wing"), "Mojang")
    val minecon2012Cape = Wing(wingTexture("minecon_2012_cape_wing"), "Mojang")
    val minecon2013Cape = Wing(wingTexture("minecon_2013_cape_wing"), "Mojang")
    val minecon2015Cape = Wing(wingTexture("minecon_2015_cape_wing"), "Mojang")
    val minecon2016Cape = Wing(wingTexture("minecon_2016_cape_wing"), "Mojang")
    val minecon2019Cape = Wing(wingTexture("minecon_2019_cape_wing"), "Mojang")
    val cobaltCape = Wing(wingTexture("cobalt_cape_wing"), "Mojang")
    val scrollsCape = Wing(wingTexture("scrolls_cape_wing"), "Mojang")
    val crowdinCape = Wing(wingTexture("crowdin_cape_wing"), "Mojang")
    val mapmakerCape = Wing(wingTexture("mapmaker_cape_wing"), "Mojang")
    val millionthCape = Wing(wingTexture("millionth_cape_wing"), "Mojang")
    val mojiraModCape = Wing(wingTexture("mojira_mod_cape_wing"), "Mojang")
    val dannybstyleCape = Wing(wingTexture("dannybstyle_cape_wing"), "Mojang")
    val julianclarkCape = Wing(wingTexture("julianclark_cape_wing"), "Mojang")
    val julianclarkCapeAlt = Wing(wingTexture("julianclark_cape_wing_alt"), "Mojang")
    val mrmessiahCape = Wing(wingTexture("mrmessiah_cape_wing"), "Mojang")
    val prismarineCape = Wing(wingTexture("prismarine_cape_wing"), "Mojang")
    val turtleCape = Wing(wingTexture("turtle_cape_wing"), "Mojang")
    val eagle = Wing(wingTexture("eagle_wing"), "Lemoncake")
    val greenwingMacaw = Wing(wingTexture("greenwing_macaw_wing"), "Lemoncake")
    val fairyonline = Wing(wingTexture("fairyonline_wing"), "Lemoncake")
    val angel = Wing(wingTexture("angel_wing"), "Lemoncake")
    val demon = Wing(wingTexture("demon_wing"), "Lemoncake")
    val phoenix = Wing(wingTexture("phoenix_wing"), "Lemoncake")
    val dragonfly = Wing(wingTexture("dragonfly_wing"), "Lemoncake")
    val greenBeetle = Wing(wingTexture("green_beetle_wing"), "Lemoncake")
    val purpleBeetle = Wing(wingTexture("purple_beetle_wing"), "Lemoncake")
    val goldenBeetle = Wing(wingTexture("golden_beetle_wing"), "Lemoncake")
    val friedChicken = Wing(wingTexture("fried_chicken_wing"), "Lemoncake")
    val greenDragon = Wing(wingTexture("green_dragon_wing"), "Lemoncake")
    val redDragon = Wing(wingTexture("red_dragon_wing"), "Lemoncake")
    val fireDragon = Wing(wingTexture("fire_dragon_wing"), "Lemoncake, AdrianTodt")
    val phantom = Wing(wingTexture("phantom_wing"), "Noatry")
    val phantomAlt = Wing(wingTexture("phantom_wing_alt"), "Shosh99")
    val phantomMembrane = Wing(wingTexture("phantom_membrane_wing"), "Trailblazer101")
    val bat = Wing(wingTexture("bat_wing"), "Lemoncake")
    val batAlt = Wing(wingTexture("bat_wing_alt"), "Doctor_CZ")
    val vex = Wing(wingTexture("vex_wing"), "The_Khuzdul1")
    val creamyWhite = Wing(wingTexture("creamy_white_wing"), "nightb0x")
    val mechDragon = Wing(wingTexture("mech_dragon_wing"), "Ontvlambaar")
    val redstone = Wing(wingTexture("redstone_wing"), "dbrighthd")
    val shulker = Wing(wingTexture("shulker_wing"), "dbrighthd")
    val tnt = Wing(wingTexture("tnt_wing"), "dbrighthd")
    val tinyBird = Wing(wingTexture("tiny_bird_wing"), "dbrighthd")
    val brazil = Wing(wingTexture("brazil_wing"), "dbrighthd")
    val usa = Wing(wingTexture("usa_wing"), "dbrighthd")
    val earth = Wing(wingTexture("earth_wing"), "Ontvlambaar")
    val rainbow = Wing(wingTexture("rainbow_wing"), "dbrighthd")
    val blackElytra = Wing(wingTexture("black_elytra_wing"), "dbrighthd")
    val blueElytra = Wing(wingTexture("blue_elytra_wing"), "dbrighthd")
    val brownElytra = Wing(wingTexture("brown_elytra_wing"), "dbrighthd")
    val cyanElytra = Wing(wingTexture("cyan_elytra_wing"), "dbrighthd")
    val grayElytra = Wing(wingTexture("gray_elytra_wing"), "dbrighthd")
    val greenElytra = Wing(wingTexture("green_elytra_wing"), "dbrighthd")
    val lightBlueElytra = Wing(wingTexture("light_blue_elytra_wing"), "dbrighthd")
    val lightGrayElytra = Wing(wingTexture("light_gray_elytra_wing"), "dbrighthd")
    val limeElytra = Wing(wingTexture("lime_elytra_wing"), "dbrighthd")
    val magentaElytra = Wing(wingTexture("magenta_elytra_wing"), "dbrighthd")
    val orangeElytra = Wing(wingTexture("orange_elytra_wing"), "dbrighthd")
    val pinkElytra = Wing(wingTexture("pink_elytra_wing"), "dbrighthd")
    val purpleElytra = Wing(wingTexture("purple_elytra_wing"), "dbrighthd")
    val redElytra = Wing(wingTexture("red_elytra_wing"), "dbrighthd")
    val whiteElytra = Wing(wingTexture("white_elytra_wing"), "dbrighthd")
    val yellowElytra = Wing(wingTexture("yellow_elytra_wing"), "dbrighthd")
    val xmasTree = Wing(wingTexture("xmas_tree_wing"), "dbrighthd")
    val xmasStar = Wing(wingTexture("xmas_star_wing"), "Ontvlambaar")
    val glider = Wing(wingTexture("glider_wing"), "dbrighthd")
    val spooky = Wing(wingTexture("spooky_wing"), "xshot_99")
    val irreality = Wing(wingTexture("irreality_wing"), null)

    private fun wingTexture(path: String) = identifier("textures/entity/$path.png")
}